### ISSUE TITLE
Syntax error in git-lfs-s3/bin/git-lfs-s3

### ISSUE THREAD

**Issue by hinder90** [meltingice/git-lfs-s3#3]
In like 20, shouldn't the : actually be an = for assigment? Even so. I get errors either way, but wanted to check

**Comment by meltingice** [comment]
That's not a syntax error. What version of Ruby are you running?

**Comment by hinder90** [comment]
ruby 1.8.7 (2013-06-27 patchlevel 374) [x86_64-linux]

Unfortunately, the ruby packages that ship with Centos are antique. What version would be ideal? I can scrub the packages and compile it from source.

**Comment by meltingice** [comment]
You'll need at least 1.9.3 but even that is ancient. I would recommend >= 2.0.0.

## 

Ryan LeFevre (@meltingice)
HODINKEE, Inc.
Sr. Software Engineer

On Thu, Jul 9, 2015 at 9:52 AM -0700, "Matthew Litwin" notifications@github.com wrote:

ruby 1.8.7 (2013-06-27 patchlevel 374) [x86_64-linux]

Unfortunately, the ruby packages that ship with Centos are antique. What version would be ideal? I can scrub the packages and compile it from source.

**Comment by meltingice** [comment]
I would also recommend looking into [RVM](http://rvm.io/) or something equivalent. Will save you a lot of headaches.

**Comment by hinder90** [comment]
Yeah, RVM definitely make development a lot more sane.

So by design, that example binary should run and serve git-lfs from the plug-in with no other software? I mean, I will need to daemonize it- probably with monit- but other than that it should be good on its own?

**Comment by meltingice** [comment]
Correct, the example binary will fire up a WEBrick server (which ships with Ruby), but as you said you will probably want to daemonize it to ensure it stays running. No other outside dependencies are required.

**Comment by hinder90** [comment]
Thanks, the issue was clearly because ruby was so old.
