### ISSUE TITLE
encryption in git-lfs-s3?

### ISSUE THREAD

**Issue by hinder90** [meltingice/git-lfs-s3#4]
Hi, is it possible to encrypt traffic between git clients and git-lfs-s3?

**Comment by meltingice** [comment]
S3 presigned URLs always use HTTPS, so the data is always encrypted en route.

**Comment by hinder90** [comment]
My concern is having an HTTP port (on port 8080) open to the world. From how I understand git-lfs-s3 works as well as what I have read on https://git-lfs.github.com/, if a person could gain access to the git-lfs-s3 server by say, sniffing the git-lfs-s3 username and password, wouldn't they be able to get the AWS credentials necessary to access the S3 bucket that git-lfs-s3 uses?

**Comment by meltingice** [comment]
You can force HTTPS to the git-lfs-s3 server by placing it behind a reverse proxy, such as nginx, or by adding a load balancer with SSL termination. That will ensure that the username and password is encrypted as well.
