### ISSUE TITLE
localhost access only?

### ISSUE THREAD

**Issue by hinder90** [meltingice/git-lfs-s3#5]
Hi, I am finding that I can only connect to git-lfs-s3 on it's configured PORT on localhost only. Even when on the server hosting git-lfs-s3, I cannot connect via its primary interface, only loopback. Is there a configuration for this?

**Comment by meltingice** [comment]
There is no configuration inside git-lfs-s3 for this.

There are 2 things this could be. Either there's a firewall rule that's preventing access to the server on your port, or you're trying to start the server on port 80 without sudo (a Linux restriction).

**Comment by hinder90** [comment]
I am running it on port 8080. Netstat shows that the service is explicitly running on localhost:8080. Normally, it would expect it to be *:8080.
